In [44]:
import pandas as pd

In [45]:
df = pd.DataFrame([[1,2,3],[4,5,3],[7,8,3]],columns=["a","b","c"],index=["x","y","z"])
df.head(3)
df.index.tolist()
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, x to z
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   a       3 non-null      int64
 1   b       3 non-null      int64
 2   c       3 non-null      int64
dtypes: int64(3)
memory usage: 96.0+ bytes

         a    b    c
count  3.0  3.0  3.0
mean   4.0  5.0  3.0
std    3.0  3.0  0.0
min    1.0  2.0  3.0
25%    2.5  3.5  3.0
50%    4.0  5.0  3.0
75%    5.5  6.5  3.0
max    7.0  8.0  3.0

In [46]:
df.unique()

AttributeError: 'DataFrame' object has no attribute 'unique'

In [ ]:
df.nunique()

a    3
b    3
c    1
dtype: int64

In [ ]:
df.shape

(3, 3)

In [ ]:
df.size

9

In [ ]:
df = pd.read_csv("https://raw.githubusercontent.com/KeithGalli/complete-pandas-tutorial/refs/heads/master/warmup-data/coffee.csv")

In [ ]:
df.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [ ]:
df.shape

(14, 3)

In [ ]:
df.size

42

In [ ]:
df.info

<bound method DataFrame.info of           Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35>

In [ ]:
df.describe

<bound method NDFrame.describe of           Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35>

In [47]:
import pandas as pd

In [48]:
coffee = pd.read_csv("https://raw.githubusercontent.com/KeithGalli/complete-pandas-tutorial/refs/heads/master/warmup-data/coffee.csv")

In [49]:
print(coffee)

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [50]:
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [51]:
coffee.tail()

         Day Coffee Type  Units Sold
9     Friday       Latte          35
10  Saturday    Espresso          45
11  Saturday       Latte          35
12    Sunday    Espresso          45
13    Sunday       Latte          35

In [57]:
coffee.sample(10,random_state=1)

          Day Coffee Type  Units Sold
3     Tuesday       Latte          20
7    Thursday       Latte          30
6    Thursday    Espresso          40
2     Tuesday    Espresso          30
10   Saturday    Espresso          45
4   Wednesday    Espresso          35
1      Monday       Latte          15
12     Sunday    Espresso          45
0      Monday    Espresso          25
13     Sunday       Latte          35

In [55]:
coffee.loc[0]

Day              Monday
Coffee Type    Espresso
Units Sold           25
Name: 0, dtype: object

In [58]:
coffee.loc[5:12]

          Day Coffee Type  Units Sold
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45

In [64]:
coffee.loc[:,["Day","Units Sold"]]

          Day  Units Sold
0      Monday          25
1      Monday          15
2     Tuesday          30
3     Tuesday          20
4   Wednesday          35
5   Wednesday          25
6    Thursday          40
7    Thursday          30
8      Friday          45
9      Friday          35
10   Saturday          45
11   Saturday          35
12     Sunday          45
13     Sunday          35

In [67]:
coffee.iloc[0:5,[0,2]]

         Day  Units Sold
0     Monday          25
1     Monday          15
2    Tuesday          30
3    Tuesday          20
4  Wednesday          35

In [68]:
coffee.index = coffee["Day"]

In [72]:
coffee.loc["Monday":"Wednesday", "Units Sold"]

Day
Monday       25
Monday       15
Tuesday      30
Tuesday      20
Wednesday    35
Wednesday    25
Name: Units Sold, dtype: int64

In [ ]:
coffee.iloc[Rows,Columns] #only using indexes values

In [ ]:
coffee.loc[1:3,"Units Sold"] = 10

In [74]:
coffee.head()

                 Day Coffee Type  Units Sold
Day
Monday        Monday    Espresso          25
Monday        Monday       Latte          15
Tuesday      Tuesday    Espresso          30
Tuesday      Tuesday       Latte          20
Wednesday  Wednesday    Espresso          35

In [78]:
coffee.iat[0,0]

'Monday'

In [ ]:
coffee["Day"]

Day
Monday          Monday
Monday          Monday
Tuesday        Tuesday
Tuesday        Tuesday
Wednesday    Wednesday
Wednesday    Wednesday
Thursday      Thursday
Thursday      Thursday
Friday          Friday
Friday          Friday
Saturday      Saturday
Saturday      Saturday
Sunday          Sunday
Sunday          Sunday
Name: Day, dtype: object

In [82]:
coffee["Units Sold"]

Day
Monday       25
Monday       15
Tuesday      30
Tuesday      20
Wednesday    35
Wednesday    25
Thursday     40
Thursday     30
Friday       45
Friday       35
Saturday     45
Saturday     35
Sunday       45
Sunday       35
Name: Units Sold, dtype: int64

In [88]:
coffee.sort_values("Units Sold")

                 Day Coffee Type  Units Sold
Day
Monday        Monday       Latte          15
Tuesday      Tuesday       Latte          20
Monday        Monday    Espresso          25
Wednesday  Wednesday       Latte          25
Tuesday      Tuesday    Espresso          30
Thursday    Thursday       Latte          30
Wednesday  Wednesday    Espresso          35
Friday        Friday       Latte          35
Sunday        Sunday       Latte          35
Saturday    Saturday       Latte          35
Thursday    Thursday    Espresso          40
Friday        Friday    Espresso          45
Saturday    Saturday    Espresso          45
Sunday        Sunday    Espresso          45

In [90]:
coffee.sort_values(["Units Sold", "Coffee Type"], ascending=[0,1])

                 Day Coffee Type  Units Sold
Day
Friday        Friday    Espresso          45
Saturday    Saturday    Espresso          45
Sunday        Sunday    Espresso          45
Thursday    Thursday    Espresso          40
Wednesday  Wednesday    Espresso          35
Friday        Friday       Latte          35
Saturday    Saturday       Latte          35
Sunday        Sunday       Latte          35
Tuesday      Tuesday    Espresso          30
Thursday    Thursday       Latte          30
Monday        Monday    Espresso          25
Wednesday  Wednesday       Latte          25
Tuesday      Tuesday       Latte          20
Monday        Monday       Latte          15